version: '3.6'
volumes:
  php-fpm-socket:
  node_modules_store:
services:
  web:
    image: nginx:latest
    container_name: sample-php-nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./server:/usr/share/nginx/html
      - node_modules_store:/usr/share/nginx/html/node_modules
    ports:
      - 8080:80
    depends_on:
      - app

  app:
    build: ./infra/docker/app
    container_name: sample-php-app
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./server:/usr/share/nginx/html
      - ./server:/work/src
    restart: always
    ports:
      - 9090:9000

  db:
    image: mysql:5.7
    container_name: sample-db-app
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_databas
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./infra/docker/mysql/data:/var/lid/mysql
    ports:
      - 3308:3306

  phpmyadmin_srv:
    image: phpmyadmin/phpmyadmin
    container_name: sample-phpmyadmin-app
    volumes:
      - ./docker/infra/phpmyadmin/sessions:/sessions
    ports:
      - 4001:80
    